### ISSUE TITLE
FAQ footer link

### ISSUE THREAD

**Issue by pablokohls** [danigro77/NWKendo#5]
Current behavior: the FAQ link on the footer leads to the Resources and FAQ section, and has the general tab open. 
Expected behavior: when clicking on the FAQ link in the footer, the link leads to the Resources aND FAQ section, but with the FAQ tab open instead of General.

**Comment by danigro77** [comment]
https://github.com/danigro77/NWKendo/issues/4 needs to be done before this one

**Comment by danigro77** [comment]
different solution - not needed anymore
